const names = [
    'Bria',
    'Marta',
    'Missouri',
    'Larue',
    'Noemy',
    'Josefa',
    'Rosa',
    'Samara',
    'Lysanne',
    'Pasquale',
    'Jeremy',
    'Lexus',
    'Freida',
    'Rafael',
    'Rubie',
    'Easton',
    'Dustin',
    'Alisa',
    'Clementina',
    'Orion',
    'Santina',
    'Dorcas',
    'Alvah',
    'Rahul',
    'Donato',
    'Barry',
    'Tito',
    'Wayne',
    'Logan',
    'Ocie',
    'Cordell',
    'Horace',
    'Joshua',
    'Francesco',
    'Leora',
    'Armand',
    'Delmer',
    'Gloria',
    'Marcella',
    'Ivory',
    'Dallas',
    'Glennie',
    'Noemie',
    'Shannon',
    'Aracely',
    'Tessie',
    'Herminio',
    'Briana',
    'Benedict',
    'Nathan',
    'Evans',
    'Camilla',
    'Hershel',
    'Titus',
    'Chauncey',
    'Katarina',
    'Sophia',
    'Griffin',
    'Immanuel',
    'Devante',
    'Elissa',
    'Chyna',
    'Danyka',
    'Eli',
    'Maurine',
    'Irving',
    'Kaycee',
    'Maryam',
    'Dayton',
    'Rosemarie',
    'Jewell',
    'Sabryna',
    'Hailie',
    'Luigi',
    'Demond',
    'Cyril',
    'Scotty',
    'Mafalda',
    'Lucienne',
    'Lonny',
    'Herta',
    'Jarred',
    'Johathan',
    'Hadley',
    'Claudine',
    'Toni',
    'Myah',
    'Drake',
    'Pink',
    'Eloise',
    'Krystina',
    'Selmer',
    'Libby',
    'Madisen',
    'Hilma',
    'Lane',
    'Barrett'
];
const surnames = [
    'King',
    'Goyette',
    'Purdy',
    'Monahan',
    'Kling',
    'Kreiger',
    'Kuhlman',
    'Denesik',
    'Thiel',
    'Moore',
    'Fisher',
    'Abernathy',
    'Cruickshank',
    'Koch',
    'Gibson',
    'Grady',
    'Aufderhar',
    'Nitzsche',
    'Kiehn',
    'Hackett',
    'Schimmel',
    'Senger',
    'Cormier',
    'Fahey',
    'Fritsch',
    'Hilpert',
    'Sauer',
    'Bernier',
    'Nicolas',
    'Frami',
    'Blick',
    'Harris',
    'Wintheiser',
    'Gaylord',
    'Rau',
    'O\'Kon',
    'Rippin',
    'Conn',
    'Abshire',
    'Zemlak',
    'Maggio',
    'Schumm',
    'Thompson',
    'Wiegand',
    'Vandervort',
    'Douglas',
    'Stoltenberg',
    'O\'Connell',
    'Yost',
    'Turcotte',
    'Cassin',
    'Schroeder',
    'Adams',
    'Cronin',
    'Keeling',
    'Keebler',
    'Wunsch',
    'Koepp',
    'Howe',
    'Grant',
    'Simonis',
    'Conroy',
    'Murphy',
    'Mitchell',
    'Larkin',
    'Mueller',
    'Emmerich',
    'Stamm',
    'Wilkinson',
    'Lynch',
    'Greenholt',
    'Macejkovic',
    'Kuphal',
    'Schuppe',
    'Runolfsdottir',
    'Ratke',
    'Swift',
    'Spinka',
    'Bergnaum',
    'Ferry',
    'Schaefer',
    'O\'Hara',
    'Stiedemann',
    'Champlin',
    'Hand',
    'Orn',
    'Williamson',
    'Green'
];
const nickEnds = [
    'autumn', 'hidden', 'bitter', 'misty', 'silent', 'empty', 'dry', 
    'dark', 'summer', 'icy', 'delicate', 'quiet', 'white', 'cool', 'spring',
    'winter', 'patient', 'twilight', 'dawn', 'crimson', 'wispy', 'weathered',
    'blue', 'billowing', 'broken', 'cold', 'damp', 'falling', 'frosty', 'green',
    'long', 'late', 'lingering', 'bold', 'little', 'morning', 'muddy', 'old',
    'red', 'rough', 'still', 'small', 'sparkling', 'throbbing', 'shy',
    'wandering', 'withered', 'wild', 'black', 'young', 'holy', 'solitary',
    'fragrant', 'aged', 'snowy', 'proud', 'floral', 'restless', 'divine',
    'polished', 'ancient', 'purple', 'lively', 'nameless', 'waterfall', 'river',
    'breeze', 'moon', 'rain', 'wind', 'sea', 'frog', 'smoke', 'star',
    'morning', 'snow', 'lake', 'sunset', 'pine', 'shadow', 'leaf', 'dawn',
    'glitter', 'forest', 'hill', 'cloud', 'meadow', 'sun', 'glade', 'bird',
    'brook', 'butterfly', 'bush', 'dew', 'dust', 'field', 'fire', 'flower',
    'firefly', 'feather', 'grass', 'haze', 'mountain', 'night', 'pond',
    'darkness', 'snowflake', 'silence', 'sound', 'sky', 'shape', 'surf',
    'thunder', 'violet', 'water', 'wildflower', 'wave', 'water', 'resonance',
    'sun', 'wood', 'dream', 'cherry', 'tree', 'fog', 'frost', 'voice', 'paper'
];
const domains = [
    'gmail.com','yahoo.com','hotmail.com','msn.com','outlook.com','live.com','me.com','aol.com','mac.com'
];

const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

const randomNumber = (from, to) =>
    Math.floor(Math.random() * (to - from + 1)) + from;

const generatePassword = (length) => {
    let password = '';
    const n = charset.length;
    for (let i = 0; i < length; i++) {
        password += charset.charAt(Math.floor(Math.random() * n));
    };
    return password;
};

let fName = '';
let lName = '';

const faker = {
    getFName: () => {
        const resultFName = names[randomNumber(0, names.length - 1)];
        fName = resultFName;

        return resultFName;
    },
    getLName: () => {
        const resultLName = surnames[randomNumber(0, surnames.length - 1)];
        lName = resultLName;

        return resultLName;
    },
    getNickname: () => `${fName}_${nickEnds[randomNumber(0, nickEnds.length - 1)]}`.toLowerCase(),
    getEmail: () => `${fName}.${lName}@${domains[randomNumber(0, domains.length - 1)]}`.toLowerCase(),
};
